# Generated by Django 4.2.2 on 2023-06-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_employee_is_full_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.CharField(choices=[('jr', 'Junior'), ('reg', 'Regular'), ('sr', 'Senior')], default='jr', max_length=25),
            preserve_default=False,
        ),
    ]
