# Generated by Django 4.2.2 on 2023-06-17 21:26

import django.core.validators
from django.db import migrations, models
import expenses_tracker.tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinValueValidator(2), expenses_tracker.tracker.validators.validate_letters]),
        ),
    ]
