# Generated by Django 4.2.2 on 2023-06-17 21:27

import django.core.validators
from django.db import migrations, models
import expenses_tracker.tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), expenses_tracker.tracker.validators.validate_letters]),
        ),
    ]
