# Generated by Django 4.2.2 on 2023-06-18 09:11

from django.db import migrations, models
import expenses_tracker.tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_profile_budget_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='profile_pic', validators=[expenses_tracker.tracker.validators.MaxFileSizeValidator(5)]),
        ),
    ]
