# Generated by Django 4.2.2 on 2023-06-18 09:17

from django.db import migrations, models
import expenses_tracker.tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic', validators=[expenses_tracker.tracker.validators.MaxFileSizeValidator(5)]),
        ),
    ]
