# Generated by Django 4.2.2 on 2023-06-15 12:35

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/', validators=[petstagram.photos.validators.validate_file_size]),
        ),
    ]
