# Generated by Django 4.2.2 on 2023-06-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='review',
            field=models.TextField(default='Test'),
        ),
    ]
