# Generated by Django 4.2.2 on 2023-06-08 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_employee_options_category_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
