# Generated by Django 4.2.2 on 2023-06-08 07:32

from django.db import migrations, models
import models_demo.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateField(validators=[models_demo.web.validators.validate_in_the_past]),
        ),
    ]
