# Generated by Django 4.2.2 on 2023-06-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_common_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
